apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dxc1dro1p-nodejs 
  janus-idp.io/tekton: dxc1dro1p-nodejs
  backstage.io/kubernetes-id: dxc1dro1p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dxc1dro1p-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  