apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dxc1dro1p-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dxc1dro1p-nodejs 
  name: dxc1dro1p-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dxc1dro1p-nodejs 
